name: artifact
version: '1.0-SNAPSHOT'
main: io.github.itokagimaru.artifact.ArtifactMain
api-version: '1.21'

depend:
  - Vault
  - MythicMobs
softdepend:
  - Vault

permissons:
  artifact.admin:
    default: op
  artifact.auction.use:
    default: true
  artifact.stash.use:
    default: true

commands:
  getNewArtifact:
    description: 新しいアーティファクトを入手する
    usage: /getnewartifact <seriesId> <slotId> <tier>
    permission: artifact.admin
    
  auction:
    description: オークションシステムを開く
    usage: /auction [search|sell|my|cancel|help]
    permission: artifact.auction.use
    aliases:
      - ah
      - market

  stash:
    description: 保管アイテムを確認・取り出す
    usage: /stash [all|count]
    permission: artifact.stash.use
    aliases:
      - storage
      - mail
